### ISSUE TITLE
Difficulty in Compiling 

### ISSUE THREAD

**Issue by GrumFoss** [mperino/ExpanseAirTank#2]
Hi I am getting multiple non return statement warnings. When uploaded to screen the screen goes black with white lines

**Comment by mperino** [comment]
It still compiles and runs fine for me.

Make sure that you have the  <Adafruit_GFX.h> and <Adafruit_ILI9341.h> libraries installed.

Please post the error messages that you get when you compile here, so that I can give more feedback.

**Comment by mperino** [comment]
@GrumFoss did the latest compile for you? can we close this out?

**Comment by mperino** [comment]
Confirmed with Grum that it compiled for him and is working.  Not sure what the underlying issue RCA is. 
Closed as FBM.
